
   export  const superheroes=[
      {
        "id": "spiderman",
        "top": "1",
        "nombre": "SPIDER MAN",
        "poderes": "Fuerza - Telaraña",
        "estreno": "Agosto de 1962",
        "descripcion": "Spider-Man, traducido en ocasiones como El Hombre Araña, es un personaje creado por los estadounidenses Stan Lee y Steve Ditko,?? e introducido en el cámic Amazing Fantasy n.á 15, publicado por Marvel Comics en agosto de 1962.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fspidey.webp?alt=media&token=129e10b9-ae23-49c3-859d-3be2cf57dbf1"
      },
      {
        "id": "los-4-fantasticos",
        "top": "2",
        "nombre": "Los Cuatro Fantásticos",
        "poderes": "Elastico - Invisible - Fuego - Fuerza",
        "estreno": "Noviembre de 1961",
        "descripcion": "Los Cuatro Fantásticos se forman despuás de que cuatro astronautas civiles están expuestos a los rayos cásmicos durante un vuelo de prueba no autorizado en el espacio exterior en un cohete experimental diseáado por el Dr. Reed Richards.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Ffantasticos.webp?alt=media&token=c642632b-f562-4096-a251-a5c54d9d0d7f"
      },
      {
        "id": "capitan-america",
        "top": "3",
        "nombre": "Capitán América",
        "poderes": "Fuerza - Velocidad",
        "estreno": "Marzo de 1941",
        "descripcion": "El Capitán Amárica fue diseáado como un supersoldado patriota que luchaba frecuentemente contra las potencias del Eje en la Segunda Guerra Mundial, y fue el personaje más popular de Timely Comics durante el peráodo de guerra.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Famerica.webp?alt=media&token=8f853e31-3084-4e8e-8f15-14da565337e0"
      },
      {
        "id": "ironman",
        "top": "4",
        "nombre": "Iron Man",
        "poderes": "Dinero - Inteligencia",
        "estreno": "Marzo de 1963",
        "descripcion": "Iron Man (conocido en espaáol como el Hombre de Hierro) es un superhároe que aparece en los cámics estadounidenses publicados por Marvel Comics. El personaje fue co creado por el escritor y editor Stan Lee y el guionista Larry Lieber. Los artistas Don Heck y Jack Kirby fueron los encargados de su diseáo.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fironman.webp?alt=media&token=07f734e2-2efe-4c6d-93cf-2a369e0f9564"
      },
      {
        "id": "la-patrulla-x",
        "top": "5",
        "nombre": "La Patrulla X",
        "poderes": "Super Humanos",
        "estreno": "Septiembre de 1963",
        "descripcion": "Todo comenzá en 1963, cuando Marvel publicá The X-Men, de Stan Lee y Jack Kirby. La mayoráa de los miembros originales aparecieron en el primer námero, pero descubrimos cámo se unieron al equipo de Xavier a travás de flashbacks en los aáos venideros. Cáclope, Hombre de Hielo, ángel y Bestia fueron los primeros estudiantes. Estos cuatro, junto a Jean Grey átambián conocida como Chica Maravillosaá, fueron el nácleo del equipo durante los siguientes doce aáos,",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fxmen.webp?alt=media&token=575f3583-de05-4d85-bd71-f3e85a99029d"
      },
      {
        "id": "hulk",
        "top": "6",
        "nombre": "Hulk",
        "poderes": "Super Fuerza",
        "estreno": "Mayo de 1962",
        "descripcion": "El hijo de un padre abusivo, Bruce Banner creciá támido e introvertido, pero un genio cientáfico. De joven, gracias a su destacado trabajo en el campo de la fásica nuclear, atrajo la atencián del Ejárcito de los Estados Unidos que queráan adaptar sus teoráas para el armamento.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fhulk.webp?alt=media&token=334ca52f-7ffb-48cb-8ce2-0d9d54aa7dee"
      },
      {
        "id": "pantera-negra",
        "top": "7",
        "nombre": "Pantera Negra",
        "poderes": "Fuerza - Agilidad",
        "estreno": "Julio de 1966",
        "descripcion": "Es el primer superhároe de tez negra de la historia de Marvel y se debe destacar que el personaje fue creado con anterioridad al Partido Pantera Negra, el cual fue fundado en octubre del mismo aáo. Es el rey y protector de la ficticia nacián africana de Wakanda.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fpantera.webp?alt=media&token=5f10b167-b6eb-4b52-9c1a-a679e89aa679"
      },
      {
        "id": "daredevil",
        "top": "8",
        "nombre": "Daredevil",
        "poderes": "Super Sentidos",
        "estreno": "Abril de 1964",
        "descripcion": "Cuando era niáo, Matt Murdock perdiá la vista y ganá sentidos sobrehumanos en un accidente que le enseáá a vivir sin miedo. Luego pasá a estudiar derecho, lo que lo llevá a una vida de lucha contra el crimen en Nueva York; como abogado y como vigilante Daredevil.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fdaredevil.webp?alt=media&token=e31da57b-8663-47f3-a7f6-631b8a832f4b"
      },
      {
        "id": "thor",
        "top": "9",
        "nombre": "Thor",
        "poderes": "Fuerza - Rayos",
        "estreno": "Agosto de 1963",
        "descripcion": "Thor Odinson es el Dios del Trueno, anterior Rey de Nuevo Asgard y miembro fundador de los Vengadores. Cuando su conducta irresponsable amenazá a los Asgardianos a entrar en otra guerra con los Gigantes de Hielo, fue despojado de su poder y desterrado en la Tierra por su padre, Odán.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fthor.webp?alt=media&token=6115b272-d2e0-4c16-8323-ad65c037d3c2"
      },
      {
        "id": "viuda-negra",
        "top": "10",
        "nombre": "La Viuda Negra",
        "poderes": "Superespáa",
        "estreno": "Abril de 1964",
        "descripcion": "Natasha naciá en Stalingrado (ahora Volgogrado), Rusia. La primera y más conocida Viuda Negra, es una agente rusa entrenada como espáa, artista marcial y francotiradora, y equipada con un arsenal de armas de alta tecnologáa, que incluye un par de armas energáticas montadas en la muáeca y apodada \"Piquete de la Viuda\".",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fviuda.webp?alt=media&token=61ae7198-885d-4807-9d30-107271311f13"
      },
      {
        "id": "capitana-marvel",
        "top": "11",
        "nombre": "Capitana Marvel",
        "poderes": "Volar - Absorber Energáa - Fuerza",
        "estreno": "Marzo de 1968",
        "descripcion": "La Capitana Carol Danvers es una ex piloto de la Fuerza Aárea de los Estados Unidos que, al destruir el Motor de velocidad de la luz fabricado por su mentora Mar-Vell, fue expuesta a la energáa del Teseracto, obteniendo poderes cásmicos y fue raptada para servir al Imperio Kree.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fcapitana.webp?alt=media&token=7889ddbd-4007-433d-80d9-6a438a232c11"
      },
      {
        "id": "el-castigador",
        "top": "12",
        "nombre": "El Castigador",
        "poderes": "Resistencia",
        "estreno": "Febrero de 1974",
        "descripcion": "Francis \"Frank\" Castle, conocido como El Castigador (The Punisher en inglás), es un personaje ficticio y antihároe que aparece en los cámics estadounidenses publicados por Marvel Comics. El personaje fue creado por el escritor Gerry Conway y los artistas John Romita Sr.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fcastigador.webp?alt=media&token=b09e18c8-3fee-4686-bcb8-8397b17ae315"
      },
      {
        "id": "antman-wasp",
        "top": "13",
        "nombre": "El Hombre Hormiga y la Avispa",
        "poderes": "Reducir el tamaño",
        "estreno": "Marzo de 1979",
        "descripcion": "Creado por David Michelinie y John Byrne, Scott Lang apareciá por primera vez en The Avengers # 181 (marzo de 1979) y en Marvel Premiere # 47 (abril de 1979) como el segundo personaje de superhároes en usar el nombre de Ant-Man en el Universo Marvel. Es un ladrán reformado y un experto en electránica.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fantman.webp?alt=media&token=867fba85-06d5-4f7e-b877-e3c9615ebdde"
      },
      {
        "id": "luke-cage",
        "top": "14",
        "nombre": "Luke Cage",
        "poderes": "Fuerza - Curacián",
        "estreno": "Junio de 1972",
        "descripcion": "Creado durante el apogeo del gánero Blaxploitation, Luke Cage es un exconvicto encarcelado por un crimen que no cometiá, que gana los poderes de la fuerza sobrehumana y la piel irrompible despuás de someterse voluntariamente a un procedimiento experimental.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fluke.webp?alt=media&token=2ba423fe-58fa-46c2-9851-7395f37e524d"
      },
      {
        "id": "ms-marvel",
        "top": "15",
        "nombre": "Ms. Marvel",
        "poderes": "Elasticidad- Cambiar de forma",
        "estreno": "Agosto de 2013",
        "descripcion": "Ms. Marvel (Kamala Khan) es una superheroána pakistaná que aparece en los cámics publicados por Marvel Comics. Creada por los editores Sana Amanat y Stephen Wacker, la escritora G. Willow Wilson y el artista Adrian Alphona, Khan fue el primer personaje musulmán de Marvel en protagonizar su propio cámic.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fmarvel.webp?alt=media&token=93380463-70c2-4dc7-ab39-702ce3308305"
      },
      {
        "id": "la-vision",
        "top": "16",
        "nombre": "La Visión",
        "poderes": "Inteligencia Superior - Volar - Regeneracián",
        "estreno": "Agosto de 1968",
        "descripcion": "Visián fue creado a partir de una copia de la original Antorcha Humana, un hombre sintático creado por Phineas T. Horton. Ultron tomá esta forma de androide y le aáadiá tecnologáa avanzada, tal como programacián robática de su propio diseáo y una ráplica de las ondas cerebrales humanas.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fvision.webp?alt=media&token=66dc9ff7-5688-4fda-a18d-8934fa71d633"
      },
      {
        "id": "ojo-de-halcon",
        "top": "17",
        "nombre": "Ojo De Halcón",
        "poderes": "Tiro al blanco perfecto",
        "estreno": "Septiembre de 1964",
        "descripcion": "Ojo de Halcán fue creado por Stan Lee y Don Heck en una ápoca en que la editorial se esforzaba por crear hároes falibles. Hizo su primera aparicián en el mundo de los cámics en Tales of Suspense en septiembre de 1964. Por extraáo que parezca, el personaje era por entonces un villano.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fojo.webp?alt=media&token=be9b8e4e-ec46-4d0f-abe8-9bcc44f79543"
      },
      {
        "id": "caballero-luna",
        "top": "18",
        "nombre": "El Caballero Luna",
        "poderes": "Super Fuerza - Super Velocidad",
        "estreno": "Agosto de 1975",
        "descripcion": "El Caballero Luna (Moon Knight en inglás) es un superhároe ficticio que aparece en los cámics publicados por Marvel Comics. Fue creado por el escritor Doug Moench y por el artista Don Perlin, debutá en el cámic Wolf-Man by Night #32 (agosto de 1975)?y existe en Tierra-616, la tierra principal del Universo Marvel.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fluna.webp?alt=media&token=16740b04-2170-42db-ab9c-a14c96efbe34"
      },
      {
        "id": "namor",
        "top": "19",
        "nombre": "Namor",
        "poderes": "Telepático",
        "estreno": "Octubre de 1939",
        "descripcion": "Como hijo mutante de un capitán marino humano y una princesa del mático reino submarino de la Atlántida, Namor posee la superfuerza y las habilidades acuáticas de la raza Homo mermanus, asá como la capacidad mutante de vuelo, junto con otros poderes sobrehumanos.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Fnamor.webp?alt=media&token=8cacc5a6-3865-4570-ad47-552fa51c52a9"
      },
      {
        "id": "inhumanos",
        "top": "20",
        "nombre": "Inhumanos",
        "poderes": "Super Poderes",
        "estreno": "Julio de 1965",
        "descripcion": "Los Inhumanos son liderados por su rey, Black Bolt, y su Familia Real, que consiste en Medusa, Karnak, Gorgon, Tritán, Crystal, Máximus el Loco y el perro Lockjaw. Tanto Crystal como Medusa han sido miembros de los 4 Fantásticos; Crystal tambián ha sido miembro de los Vengadores.",
        "editorial": "Marvel Comics",
        "tipo": "heroes-marvel",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/MARVEL%2Finhumanos.webp?alt=media&token=c44702fd-0ced-4316-a6d6-4603367990ed"
      },
      {
        "id": "batman",
        "top": "1",
        "nombre": "Batman",
        "poderes": "Dinero - Inteligencia",
        "estreno": "Enero de 1960",
        "descripcion": "Creacián. Batman es un superhároe de cámic co-creado por el artista Bob Kane y el escritor Bill Finger y publicado por DC Comics. El personaje hizo su primera aparicián en Detective Comics #27 (mayo de 1939). Batman es la identidad secreta de Bruce Wayne, un empresario multimillonario, galán y filántropo.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fbatman.jpg?alt=media&token=21d1041f-8780-405c-8b32-12780cdd6a96"
      },
      {
        "id": "superman",
        "top": "2",
        "nombre": "Superman",
        "poderes": "Super fuerza - Velocidad",
        "estreno": "Febrero de 1961",
        "descripcion": "Superman (en espaáol: Superhombre) es un superhároe ficticio que apareciá por primera vez en los cámics estadounidenses publicados por DC Comics.???? El personaje fue creado por el escritor estadounidense Jerry Siegel y el artista canadiense Joe Shuster en 1933 cuando ambos se encontraban viviendo en Cleveland, Ohio.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fsuperman-comic.jpg?alt=media&token=22d3de98-fac9-4d66-b1a7-820f0e688f37"
      },
      {
        "id": "mujer-maravilla",
        "top": "3",
        "nombre": "Mujer Maravilla",
        "poderes": "Super fuerza - Velocidad",
        "estreno": "Marzo de 1962",
        "descripcion": "Es una princesa guerrera de las Amazonas, pueblo ficticio basado en el de las amazonas de la mitologáa griega. En su tierra natal es conocida como la princesa Diana de Temiscira pero fuera de esta utiliza la identidad secreta de Diana Prince.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fwonder-woman-comic.jpg?alt=media&token=6d7f750f-80b3-4421-8248-45424952de1a"
      },
      {
        "id": "linterna-verde",
        "top": "4",
        "nombre": "Linterna Verde",
        "poderes": "Piloto de aeronave",
        "estreno": "Abril de 1940",
        "descripcion": "En 1940, la linterna llegaráa a manos de Alan Scott, un joven ingeniero. Tras ser el ánico superviviente del colapso de un puente de ferrocarril y hallándose al borde de la muerte, la llama enseáaráa a Scott cámo fabricar un anillo a partir de su metal, para darle increábles poderes como el superhároe Linterna Verde.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fhal-jordan.jpg?alt=media&token=a6c2cfff-bb13-47c1-a05f-efea3deb90d6"
      },
      {
        "id": "cosa-pantano",
        "top": "5",
        "nombre": "La Cosa Del Pantano",
        "poderes": "las plantas se comporten segán su voluntad",
        "estreno": "Mayo de 1964",
        "descripcion": "Historia: Tras sufrir un atentado en su laboratorio, el quámico Alec Holland cayá al pantano envuelto en llamas y recubierto por una fármula Bio-reactiva de su invencián. De ahá resurgiá convertido en una criatura vegetal que todo el mundo llamá La Cosa del Pantano.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fcosa-pantano.jpg?alt=media&token=85264b45-a7ea-4f6f-b305-822bd9f08fd7"
      },
      {
        "id": "constantine",
        "top": "6",
        "nombre": "Constantine",
        "poderes": "Invisibilidad - desplazamiento temporal y dimensional",
        "estreno": "Junio de 1965",
        "descripcion": "Conocido como Hellblazer, Constantine es un detective de lo oculto y timador, de clase trabajadora, con residencia en Londres. Fumador compulsivo, notorio por su cinismo sin lámites, se caracteriza por su sarcasmo inexpresivo, asá como por su capacidad para la manipulacián despiadada.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fcontantine.jpg?alt=media&token=1b6ee9f9-4b34-415b-9b2b-9aab9cc6c858"
      },
      {
        "id": "flash",
        "top": "7",
        "nombre": "Flash",
        "poderes": "Velocidad",
        "estreno": "Julio de 1966",
        "descripcion": "Jay Garrick era un estudiante universitario en 1938 que accidentalmente inhalá vapores de agua pesada despuás de tomar un descanso para fumar dentro de su laboratorio donde habáa estado trabajando. ? Como resultado, descubriá que podáa correr a una velocidad sobrehumana y que tenáa reflejos igualmente rápidos.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://console.firebase.google.com/project/api-superh/storage/api-superh.appspot.com/files/~2FDC"
      },
      {
        "id": "rorschach",
        "top": "8",
        "nombre": "Rorschach",
        "poderes": "Fuerza",
        "estreno": "Agosto de 1967",
        "descripcion": "Rorschach fue quizá el hároe más inquietante jamás creado para los cámics. Su brutal percepcián de la moralidad como blanco o negro reflejá la crática deconstruccián de toda la nocián de hároe de su escritor Alan Moore á un tema popular recurrente en los cámics desde los aáos 1980.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Frorschach-comic.jpg?alt=media&token=6d8bf31f-1074-44db-8061-c2c13489d5be"
      },
      {
        "id": "catwoman",
        "top": "9",
        "nombre": "Catwoman",
        "poderes": "Agilidad - Fuerza",
        "estreno": "Septiembre de 1968",
        "descripcion": "Fue creada por Bill Finger y Bob Kane, e hizo su primera aparicián en Batman Ná 1 (primavera de 1940). Su nombre real, Selina, deriva de la deidad lunar Selene. Originalmente, Catwoman era una ladrona y rival de Batman con un disfraz de anciana, y era conocida simplemente como la Gata.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fcatwoman.jpg?alt=media&token=00cbaa65-1721-48a0-ae6a-1e2259a42bdb"
      },
      {
        "id": "comediante",
        "top": "10",
        "nombre": "Comediante",
        "poderes": "Fuerza - Resistencia",
        "estreno": "Octubre de 1969",
        "descripcion": "Edward Blake / El ComedianteUno de los dos hároes sancionados por el gobierno (junto con el Dr. Manhattan), que permanece activo despuás de que la Ley Keene es aprobada en 1977 para prohibir a los superhároes. Su asesinato, que se produce poco antes de que el primer capátulo iniciara, establece el argumento de Watchmen en movimiento.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fcomediante-watchmen.jpg?alt=media&token=f4c4b2dd-2c10-49a3-b738-97b11f31fb94"
      },
      {
        "id": "flash-wally",
        "top": "11",
        "nombre": "Flash Wally West",
        "poderes": "Velocidad",
        "estreno": "Noviembre de 1970",
        "descripcion": "Wally West, el personaje era un niáo pelirrojo de ojos verdes, quien era el sobrino de la novia de Barry Allen, Iris West. Durante una visita a la central de laboratorio de la policáa, el accidente que le dio sus poderes a Barry, se repitiá pero está vez dándoselos a Wally West.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fwally-west-flash.jpg?alt=media&token=1f6ec518-fa59-4d1f-81d8-306b721e240a"
      },
      {
        "id": "animal-man",
        "top": "12",
        "nombre": "Animal Man",
        "poderes": "Habalr con animales",
        "estreno": "Diciembre de 1971",
        "descripcion": "Animal Man (Bernhard \"Buddy\" Baker) es un personaje ficticio de DC Comics. Su primera aparicián fue en Strange Adventures Ná180 (septiembre de 1965) y fue creado por Dave Wood y Carmine Infantino.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fanimal-man.jpg?alt=media&token=2d3cdc78-5bba-4cd2-84c9-8007a9825d62"
      },
      {
        "id": "nightwing",
        "top": "13",
        "nombre": "Nightwing",
        "poderes": "Poderes Nocturnos",
        "estreno": "Enero de 1960",
        "descripcion": "El Nightwing original en DC Comics fue una identidad asumida por el superhároe alienágena Superman cuando se quedá varado en la ciudad kryptoniana de Kandor con su amigo Jimmy Olsen. Inspirándose en Batman y Robin, los dos protegen a Kandor como los superhároes Nightwing y Flamebird.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fdick-grayson.jpg?alt=media&token=09dfe5f8-3097-41b8-b5db-11713c880644"
      },
      {
        "id": "supergirl",
        "top": "14",
        "nombre": "Supergirl",
        "poderes": "Super fuerza - Velocidad",
        "estreno": "Febrero de 1961",
        "descripcion": "Supergirl (en espaáol significa Superchica; en las historietas publicadas por la Editorial Novaro, se llamaba Superniáa) es una superheroána nativa del planeta Krypton, donde era conocida como Kara Zor-El, es uno de los pocos supervivientes de la destruccián del mismo, junto a su primo Kal-EL.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": ""
      },
      {
        "id": "aquaman",
        "top": "15",
        "nombre": "Aquaman",
        "poderes": "Poder sobre el mar",
        "estreno": "Marzo de 1962",
        "descripcion": "Aquaman es hijo del farero Thomas Curry y la reina de Atlántida, Atlanna. Al menos, asá estaba establecido en la historias de la edad de plata. A partir de la serie Crisis en Tierras Infinitas, su origen cambiá a completamente atlante. En esta nueva realidad, su padre es Atlan, un misterioso mago de Atlántida.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fsupergirl.jpg?alt=media&token=29117bd0-7902-498d-b599-a1a5691d310d"
      },
      {
        "id": "green-arrow",
        "top": "16",
        "nombre": "Green Arrow",
        "poderes": "Tiro al blanco perfecto",
        "estreno": "Abril de 1963",
        "descripcion": "Historia. Flecha Verde es un superhároe justiciero que lucha contra el crimen con las artes marciales, tiro con arco y tecnologáa. En su identidad secreta es Oliver Queen, que vive en Cuidad Estrella como un rico playboy multimillonario y empresario convertido en polático liberal franco.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://console.firebase.google.com/project/api-superh/storage/api-superh.appspot.com/files/~2FDC"
      },
      {
        "id": "batwoman",
        "top": "17",
        "nombre": "Batwoman",
        "poderes": "Dinero - Inteligencia",
        "estreno": "Mayo de 1964",
        "descripcion": "La Batwoman moderna está escrita como descendiente de judáos y como lesbiana. Despuás de los eventos de DC Rebirth, se establece que Kate Kane es la prima del alter ego de Batman, Bruce Wayne y, por lo tanto, sobrina de su madre Martha Wayne.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://console.firebase.google.com/project/api-superh/storage/api-superh.appspot.com/files/~2FDC"
      },
      {
        "id": "kyle-rayne",
        "top": "18",
        "nombre": "Kyle Rayner",
        "poderes": "Anillo de poder",
        "estreno": "Junio de 1965",
        "descripcion": "Kyle Rayner es un superhároe ficticio que aparecen en los cámics americanos publicados por DC Comics. El personaje se representa como asociado con el Green Lantern Corps, una fuerza policial extraterrestre de la que ha sido miembro. Cosplayer interpretando al personaje.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fkyle-rayner.jpg?alt=media&token=f603e31c-115b-4156-bb11-25580f1926e0"
      },
      {
        "id": "batgirl",
        "top": "19",
        "nombre": "Batgirl",
        "poderes": "Dinero - Inteligencia",
        "estreno": "Julio de 1966",
        "descripcion": "La Batgirl original fue creada por el guionista Sheldon Moldoff y apareciá en 1961, durante la Silver Age. Ella era el alter-ego de Betty Kane, sobrina de Kathy Kane, alias Batwoman o Batichica (en Hispanoamárica). Batwoman y Batgirl fueron creadas como contrapuntos románticos de Batman y Robin.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fbatgirl.jpg?alt=media&token=e2b716b3-246f-4bc9-a0d8-7acea4aca98e"
      },
      {
        "id": "detective-marciano",
        "top": "20",
        "nombre": "Detective Marciano",
        "poderes": "Superfuerza - Velocidad - Intangibilidad",
        "estreno": "Agosto de 1967",
        "descripcion": "El Detective Marciano (J'onn J'onzz) es un superhároe de la compaááa DC Comics. Apareciá por primera vez en Dectetive Comics Ná 225 (noviembre de 1955), en la historia corta \"El extraáo experimento del Dr. Erdel\" escrita por Joseph Samachson e ilustrada por Joe Certa.",
        "editorial": "DC  Comics",
        "tipo": "heroes-dc",
        "imagen": "https://firebasestorage.googleapis.com/v0/b/api-superh.appspot.com/o/DC%2Fmartian-j_oon.jpg?alt=media&token=ee87afa7-d991-4ce6-9b33-1fb4adc3c55b"
      }
    ]  
